// Generated by tokens/palette.mjs from Capsomer's tokens (every family, both themes).
// Do not edit: change the script and run `npm run tokens`. `npm run check` refuses a file that differs.
export type EmailFamily = "purple" | "fox" | "teal";
export type EmailColours = Record<"ground" | "surface" | "line" | "text" | "muted" | "accent-text" | "primary" | "primary-fg" | "ok" | "ok-soft" | "warn" | "warn-soft" | "crit" | "crit-soft" | "info" | "info-soft", string>;
export const emailColours: Record<EmailFamily, { light: EmailColours; dark: EmailColours }> = {
  "purple": {
    "light": {
      "ground": "#fbf9ff",
      "surface": "#fdfdfe",
      "line": "#dfdce5",
      "text": "#1c1727",
      "muted": "#686471",
      "accent-text": "#4f2d7f",
      "primary": "#7d50c1",
      "primary-fg": "#fdfdfe",
      "ok": "#047735",
      "ok-soft": "#d6f7dc",
      "warn": "#8a5f01",
      "warn-soft": "#ffeaca",
      "crit": "#ae453f",
      "crit-soft": "#fee7e4",
      "info": "#2668b6",
      "info-soft": "#e2eeff"
    },
    "dark": {
      "ground": "#0e0c12",
      "surface": "#18161c",
      "line": "#343238",
      "text": "#efedf3",
      "muted": "#96949e",
      "accent-text": "#c6b1f2",
      "primary": "#9b6ee3",
      "primary-fg": "#0e0c12",
      "ok": "#4aa462",
      "ok-soft": "#15301b",
      "warn": "#bc861a",
      "warn-soft": "#362508",
      "crit": "#d97269",
      "crit-soft": "#3e1e1c",
      "info": "#5793df",
      "info-soft": "#172a41"
    }
  },
  "fox": {
    "light": {
      "ground": "#fef9f7",
      "surface": "#fefdfd",
      "line": "#e5dcd8",
      "text": "#26160f",
      "muted": "#71635e",
      "accent-text": "#822e02",
      "primary": "#b64404",
      "primary-fg": "#fefdfd",
      "ok": "#057835",
      "ok-soft": "#d6f7dc",
      "warn": "#8a5f01",
      "warn-soft": "#ffeaca",
      "crit": "#af453f",
      "crit-soft": "#fee7e4",
      "info": "#2668b6",
      "info-soft": "#e2eeff"
    },
    "dark": {
      "ground": "#120c09",
      "surface": "#1c1513",
      "line": "#38312e",
      "text": "#f3edea",
      "muted": "#9e938e",
      "accent-text": "#f2aa8d",
      "primary": "#dd5f25",
      "primary-fg": "#120c09",
      "ok": "#4aa462",
      "ok-soft": "#15301b",
      "warn": "#bc861a",
      "warn-soft": "#362508",
      "crit": "#d87269",
      "crit-soft": "#3e1e1c",
      "info": "#5793df",
      "info-soft": "#172a41"
    }
  },
  "teal": {
    "light": {
      "ground": "#f1fdfd",
      "surface": "#fbfefe",
      "line": "#d5e1e1",
      "text": "#071f20",
      "muted": "#59696a",
      "accent-text": "#01585c",
      "primary": "#077478",
      "primary-fg": "#fbfefe",
      "ok": "#037936",
      "ok-soft": "#d6f7dc",
      "warn": "#8b6003",
      "warn-soft": "#ffeaca",
      "crit": "#b04540",
      "crit-soft": "#fee7e4",
      "info": "#2769b7",
      "info-soft": "#e2eeff"
    },
    "dark": {
      "ground": "#070f0f",
      "surface": "#111919",
      "line": "#2c3535",
      "text": "#e9f0f0",
      "muted": "#8b9999",
      "accent-text": "#97c8cb",
      "primary": "#249398",
      "primary-fg": "#070f0f",
      "ok": "#4aa462",
      "ok-soft": "#15301b",
      "warn": "#be881d",
      "warn-soft": "#362508",
      "crit": "#db746b",
      "crit-soft": "#3e1e1c",
      "info": "#5894df",
      "info-soft": "#172a41"
    }
  }
};
