// Generated by tokens/palette.mjs from Capsomer's tokens (the purple family, both themes).
// Do not edit: change the script and run `npm run tokens`. `npm run check` refuses a file that
// differs, and CI runs Enarratio's own checkTheme on it (test/unit/enarratio-theme.test.mjs).
// Hand it to Enarratio: `stylesheet(capsomerTheme)`, or `baseStylesheet()` with css/enarratio.css.
/** @type {import("./enarratio-theme.d.mts").EnarratioTheme} */
export const capsomerTheme = {
  "name": "capsomer",
  "fonts": {
    "body": "\"Schibsted Grotesk\", \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif",
    "numeric": "\"Schibsted Grotesk\", \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif"
  },
  "gridlines": "y",
  "light": {
    "background": "#fdfdfe",
    "text": "#1c1727",
    "mutedText": "#686471",
    "grid": "#dfdce5",
    "focus": "#8c5fd2",
    "series": [
      "#8c5fd2",
      "#cc4f0c",
      "#008489",
      "#749455",
      "#505ca1",
      "#046d5e",
      "#c564a1",
      "#98445b"
    ],
    "sequential": [
      "#e4dcf8",
      "#c7b6ec",
      "#a98dde",
      "#865cc8",
      "#5d3497"
    ],
    "status": {
      "good": "#047735",
      "warning": "#8a5f01",
      "bad": "#ae453f",
      "unknown": "#696571"
    }
  },
  "dark": {
    "background": "#18161c",
    "text": "#efedf3",
    "mutedText": "#96949e",
    "grid": "#343238",
    "focus": "#8c5fd2",
    "series": [
      "#8c5fd2",
      "#cc4f0c",
      "#008489",
      "#a3c584",
      "#a4b5ff",
      "#65cbb6",
      "#c3629f",
      "#e4889e"
    ],
    "sequential": [
      "#33254b",
      "#553e7d",
      "#7b59b2",
      "#a582e5",
      "#cdb5ff"
    ],
    "status": {
      "good": "#4aa462",
      "warning": "#bc861a",
      "bad": "#d97269",
      "unknown": "#898790"
    }
  }
};
