// Every token that is not a colour: space, radius, type, control size, motion, layers,
// focus, the reading context, and the two contexts' aliases. `node tokens/scale.mjs` writes
// tokens/scale.css, tokens/themes.css and tokens/tokens.json; `--check` regenerates them in
// memory and refuses any difference from the committed files.
//
// The values and their reasons are in capsomer/research/design.md, section 1.5, as approved
// on 2026-09-30. Each is a default: change it here, run `npm run tokens`, and record why.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { LEGACY_SEED as SEED, legacyThemes as themes } from "./palette.mjs";

const here = (p) => fileURLToPath(new URL(p, import.meta.url));

// [name, value, what it is for]. Names are short on purpose (decision 2): an app renames
// its own colliding tokens when it adopts.
export const SCALE = {
  space: [
    ["space-1", "2px", "hairline gaps: an icon beside its count"],
    ["space-2", "4px", "inside a control: icon to label"],
    ["space-3", "8px", "between controls in a toolbar"],
    ["space-4", "12px", "between rows of a form, cell padding"],
    ["space-5", "16px", "panel padding, the page gutter on a phone"],
    ["space-6", "24px", "between panels, the page gutter"],
    ["space-7", "32px", "between sections"],
    ["space-8", "48px", "between major regions of a reading page"],
    ["space-9", "64px", "above a page footer"],
  ],
  radius: [
    ["radius-s", "3px", "kbd, chips inside text"],
    ["radius-m", "6px", "controls"],
    ["radius-l", "10px", "panels and dialogs"],
    ["radius-full", "999px", "pills and switches"],
  ],
  type: [
    ["fs-label", "11px", "column labels and section titles, uppercase; nothing is set smaller"],
    ["fs-detail", "12px", "the line under a row title"],
    ["fs-body", "13px", "app body and rows"],
    ["fs-lead", "15px", "a page's lead line"],
    ["fs-h3", "18px", "a panel or dialog title"],
    ["fs-h2", "22px", "a page title in the app"],
    ["fs-prose", "clamp(17px, 1rem + 0.25vw, 19px)", "body text in the reading context"],
    ["fs-prose-h2", "clamp(22px, 1.2rem + 1.2vw, 30px)", "a heading in the reading context"],
    ["fs-input-coarse", "16px", "a form input on a touch screen, so iOS does not zoom"],
    ["prose", '"Source Serif 4", "Iowan Old Style", Charter, Georgia, serif', "long-form text and public headings (decision 5)"],
  ],
  control: [
    ["control-h", "32px", "a control's height with a fine pointer"],
    ["control-h-coarse", "44px", "a control's height with a coarse pointer"],
    ["target", "24px", "the smallest hit area, WCAG 2.5.8"],
  ],
  motion: [
    ["dur-fast", "100ms", "feedback: hover, press, a switch moving"],
    ["dur-base", "200ms", "a panel, dialog or menu opening"],
    ["dur-slow", "400ms", "a page-level change"],
    ["ease-out", "cubic-bezier(0, 0, 0.38, 0.9)", "things arriving"],
    ["ease-in-out", "cubic-bezier(0.2, 0, 0.38, 0.9)", "things moving within the page"],
  ],
  layer: [
    ["z-base", "0", "the page"],
    ["z-sticky", "20", "a sticky top bar or anchor bar"],
    ["z-tabbar", "30", "the phone tab bar"],
    ["z-overlay", "40", "a scrim and a side panel"],
    ["z-message", "70", "the status region"],
    ["z-tip", "80", "a tooltip"],
  ],
  focus: [
    ["focus-width", "2px", "the focus ring, WCAG 2.4.13's 2 px perimeter"],
    ["focus-offset", "2px", "space between the control and its ring"],
    ["focus-color", "var(--accent)", "checked at 3:1 on the surface by palette.mjs"],
  ],
  layout: [
    ["measure", "66ch", "a reading line (Bringhurst's 66 characters)"],
    ["rail-w", "208px", "the shell's left menu, expanded"],
    ["rail-w-collapsed", "56px", "the shell's left menu, collapsed to icons"],
    ["top-h", "44px", "the shell's top bar (the Portal's, #215)"],
  ],
};

// The two contexts (design 1.4): components read only these aliases, so one attribute
// on a root or a region switches between dense app UI and a reading page.
export const CONTEXTS = {
  app: [
    ["text-size", "var(--fs-body)"],
    ["leading", "1.45"],
    ["gap", "var(--space-4)"],
    ["control", "var(--control-h)"],
    ["face", "var(--ui)"],
  ],
  prose: [
    ["text-size", "var(--fs-prose)"],
    ["leading", "1.6"],
    ["gap", "var(--space-6)"],
    ["control", "40px"],
    ["face", "var(--prose)"],
  ],
};

const HEADER = (what) =>
  `/* Generated by tokens/scale.mjs (${what}). Do not edit: change the script and run
   \`npm run tokens\`. \`npm run check\` refuses a file that differs from what it writes. */\n`;

export function renderScale() {
  const lines = [];
  for (const [group, rows] of Object.entries(SCALE)) {
    lines.push(`  /* ${group} */`);
    for (const [name, value] of rows) lines.push(`  --${name}: ${value};`);
  }
  const alias = (rows, indent) => rows.map(([n, v]) => `${indent}--${n}: ${v};`).join("\n");
  return `${HEADER("space, radius, type, control, motion, layers, focus, layout")}:root {
${lines.join("\n")}
${alias(CONTEXTS.app, "  ")}
}
[data-context="prose"] {
${alias(CONTEXTS.prose, "  ")}
}
@media (pointer: coarse) {
  :root {
    --control-h: var(--control-h-coarse);
    --target: 44px;
  }
}
`;
}

// Until the family scale's failing pairs are settled (rulings.md rule 14), the committed
// colours are the legacy generator's, and these files follow them.
// The two themes pinned to an element, for the site's side-by-side specimens:
// <div data-cap-theme="dark"> shows the dark theme whatever the page's theme is.
export function renderThemes(seed = SEED) {
  const t = themes(seed);
  const block = (name) =>
    `[data-cap-theme="${name}"] {\n${t.order.map((k) => `  --${k}: ${t[name].tokens[k]};`).join("\n")}\n  color-scheme: ${name};\n  color: var(--text);\n  background: var(--ground);\n}`;
  return `${HEADER(`both themes pinned to an element, from the seed ${t.seed}`)}${block("light")}\n${block("dark")}\n`;
}

// The same values in the Design Tokens Community Group format (2025.10), for tools that
// read it. The CSS is the contract; nothing in Capsomer reads this file (decision 15).
export function renderJson(seed = SEED) {
  const t = themes(seed);
  const out = { $description: "Capsomer tokens. Generated by tokens/scale.mjs; the CSS files are the contract." };
  const typeOf = (group) => ({ space: "dimension", radius: "dimension", control: "dimension", motion: undefined, layer: "number", focus: undefined, layout: undefined, type: undefined })[group];
  for (const [group, rows] of Object.entries(SCALE)) {
    out[group] = {};
    for (const [name, value, why] of rows) {
      const ty = name.startsWith("dur-") ? "duration" : name.startsWith("ease-") ? "cubicBezier" : typeOf(group);
      let v = value;
      if (ty === "dimension" && /^\d+px$/.test(value)) v = { value: Number(value.slice(0, -2)), unit: "px" };
      else if (ty === "duration") v = { value: Number(value.slice(0, -2)), unit: "ms" };
      else if (ty === "cubicBezier") v = value.match(/[\d.]+/g).map(Number);
      else if (ty === "number") v = Number(value);
      out[group][name] = { ...(ty ? { $type: ty } : {}), $value: v, $description: why };
    }
  }
  for (const scheme of ["light", "dark"]) {
    out[`colour-${scheme}`] = {};
    for (const k of t.order) out[`colour-${scheme}`][k] = { $type: "color", $value: t[scheme].tokens[k] };
  }
  return JSON.stringify(out, null, 2) + "\n";
}

const FILES = [
  ["scale.css", renderScale],
  ["themes.css", () => renderThemes()],
  ["tokens.json", () => renderJson()],
];

export function check() {
  const problems = [];
  for (const [file, make] of FILES) {
    let committed = null;
    try {
      committed = readFileSync(here(`./${file}`), "utf8");
    } catch {
      problems.push(`tokens/${file} is missing; run npm run tokens`);
      continue;
    }
    if (committed !== make()) problems.push(`tokens/${file} differs from what tokens/scale.mjs writes; run npm run tokens`);
  }
  return problems;
}

if (process.argv[1] && fileURLToPath(import.meta.url).replace(/\\/g, "/").toLowerCase() === process.argv[1].replace(/\\/g, "/").toLowerCase()) {
  if (process.argv.includes("--check")) {
    const problems = check();
    if (problems.length) {
      console.error(`scale: ${problems.length} problem(s)\n  ${problems.join("\n  ")}`);
      process.exit(1);
    }
    console.log("scale: tokens/scale.css, themes.css and tokens.json match the script");
  } else {
    for (const [file, make] of FILES) writeFileSync(here(`./${file}`), make());
    console.log("scale: wrote tokens/scale.css, tokens/themes.css and tokens/tokens.json");
  }
}
